### ISSUE TITLE
java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableSet com.google.common.graph.Graphs.reachableNodes(com.google.common.graph.Graph, java.lang.Object)'

### ISSUE THREAD

**Issue by EdricChan03** [autonomousapps/dependency-analysis-gradle-plugin#1240]
**Build scan link**
* [Most recent build scan](https://scans.gradle.com/s/xlfklntzoc7au)
* [Original build scan when bumping to v1.33.0 from an automated Dependabot pull request](https://gradle.com/s/cgfgwbz7f7uhc)

**Plugin version**
v1.33.0

**Gradle version**
v8.10

**JDK version**
17.x

**(Optional) Kotlin and Kotlin Gradle Plugin (KGP) version**
2.0.0

**(Optional) Android Gradle Plugin (AGP) version**
8.7.0-alpha06

**(Optional) `reason` output for bugs relating to incorrect advice**

**Describe the bug**
When updating my project to use the latest v1.33.0, I get the following error when running the `buildHealth` Gradle task:

```
Execution failed for task ':core:deeplink:computeAdvice'.
> A failure occurred while executing com.autonomousapps.tasks.ComputeAdviceTask$ComputeAdviceAction
   > 'com.google.common.collect.ImmutableSet com.google.common.graph.Graphs.reachableNodes(com.google.common.graph.Graph, java.lang.Object)'
```

Viewing the build scan sheds more insight into the cryptic failure message:

```
Caused by: java.lang.NoSuchMethodError: 'com.google.common.collect.ImmutableSet com.google.common.graph.Graphs.reachableNodes(com.google.common.graph.Graph, java.lang.Object)'
  at com.autonomousapps.graph.Graphs.reachableNodes(Graphs.kt:16)
  at com.autonomousapps.graph.Graphs.reachableNodes$default(Graphs.kt:15)
  at com.autonomousapps.internal.Bundles$Companion.of(Bundles.kt:114)
  at com.autonomousapps.tasks.ComputeAdviceTask$ComputeAdviceAction.execute(ComputeAdviceTask.kt:171)
  ...
```

**To Reproduce**
1. Use v1.32.0 in a project
2. Bump to v1.33.0
3. Notice build errors when running the `buildHealth` Gradle task

**Expected behavior**
No build errors should occur when running the `buildHealth` Gradle task

**Additional context**
The issue started happening when bumping your plugin to the latest v1.33.0, as evidenced by this [GitHub Actions workflow run](https://github.com/EdricChan03/studybuddy-android/actions/runs/10416143586)

**Comment by autonomousapps** [comment]
The issue is that you have Guava 32.0.1-jre on your classpath, from buildSrc, when this plugin expects version 33.1.0-jre. You can fix by adding this:
```kotlin
// buildSrc/build.gradle.kts
dependencies {
  implementation("com.google.guava:guava:33.1.0-jre")
}
```

I learned this by debugging:
```
com.google.common.graph.Graphs::class.java.protectionDomain.codeSource.location
=> file:/path/to/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/32.0.1-jre/6e5d51a72d142f2d40a57dfb897188b36a95b489/guava-32.0.1-jre.jar
```
and then
```
com.google.common.graph.Graphs::class.java.classLoader
=> ClassLoaderScopeIdentifier.Id{coreAndPlugins:settings[:]:buildSrc[:](export)}
```

**Comment by guuilp** [comment]
Hey @autonomousapps ! I'm facing the same error, but the difference is that I don't explicit declare guava on my project. I tried adding this to root/build.gradle, but didn't work:

```
allprojects {
  configurations.all {
    resolutionStrategy {
      force("com.google.guava:guava:33.1.0-jre")
    }
  }
}
```

Unfortunately, this is a big project and I'm not sure how to create a repro, but I can answer any questions about our gradle setup.

**Comment by WebTiger89** [comment]
Still not fixed in 2.3.0

**Comment by autonomousapps** [comment]
It is not a bug in the plugin, it is an issue with your build script classpath. See https://github.com/autonomousapps/dependency-analysis-gradle-plugin/pull/1296 and the linked issue.

**Comment by autonomousapps** [comment]
Duplicate of https://github.com/autonomousapps/dependency-analysis-gradle-plugin/issues/1288
